# Overview: build and create a release via Google Cloud Deploy for GKE
# NOTE: currently requires SCM triggering due to dependency on the COMMIT_SHA variable
# Update these values, if desired
substitutions:
  _REPO_NAME: maven-demo-app
  _APP_NAME: myspringbootapp
  _DIR: .
  _PIPELINE_NAME: security-demo-pipeline
steps:
  # Retrieve the image
  - name: gcr.io/cloud-builders/docker
    entrypoint: /bin/bash
    args:
    - -c
    - |
      docker pull us-central1-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_APP_NAME}:${COMMIT_SHA} &&
      docker image inspect us-central1-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_APP_NAME}:${COMMIT_SHA} --format '{{index .RepoDigests 0}}' > image-digest.txt &&
      cat image-digest.txt
    id: digest
  # QA Sign the image 
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/bash
    args:
    - -c
    - |
      gcloud beta container binauthz attestations sign-and-create \
        --project "$PROJECT_ID" \
        --artifact-url $(/bin/cat image-digest.txt) \
        --attestor "qa_attestor" \
        --attestor-project "$PROJECT_ID" \
        --keyversion "1" \
        --keyversion-key "qa-signer" \
        --keyversion-location "us-central1" \
        --keyversion-keyring "binauthz" \
        --keyversion-project "$PROJECT_ID"
    id: qasign
    waitFor: ['digest']
images:
- us-central1-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_APP_NAME}:${COMMIT_SHA}
options:
  requestedVerifyOption: VERIFIED
  pool:
    name: 'projects/$PROJECT_ID/locations/us-central1/workerPools/private-pool'