apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: myspringbootapp
build:
  # local: 
  #   push: false
  artifacts:
  - image: myspringbootapp
    context: myspringbootapp
    docker:
      dockerfile: Dockerfile    
    sync:
      auto: true      
deploy:
   kubectl:
    manifests: ["k8s/*.yaml"]
profiles:
  - name: dev
    deploy:
      kubectl:
       manifests:
         - k8s-*
  - name: test
    deploy:
      kubectl:
        manifests:
         - k8s-*
  - name: staging
    deploy:
      kubectl:
        manifests:
         - k8s-*
  - name: prod
    deploy:
      kubectl:
        manifests:
         - k8s-*
portForward:
- resourceType: deployment
  resourceName: k8s-boot
  port: 8080