apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: myspringbootapp
build:
  # local: 
  #   push: false
  artifacts:
  - image: myspringbootapp
    context: myspringbootapp
    docker:
      dockerfile: Dockerfile    
    sync:
      auto: true      
deploy:
  kustomize:
    paths:
      - k8s/overlays/dev
profiles:
  - name: dev
    deploy:
      kustomize:
        paths:
          - k8s/overlays/dev
  - name: test
    deploy:
      kustomize:
        paths:
          - k8s/overlays/test
  - name: staging
    deploy:
      kustomize:
        paths:
          - k8s/overlays/staging
  - name: prod
    deploy:
      kustomize:
        paths:
          - k8s/overlays/prod
portForward:
- resourceType: deployment
  resourceName: myspringbootapp
  port: 8080