apiVersion: kritis.grafeas.io/v1beta1
kind: VulnzSigningPolicy
metadata:
  name: my-vsp
spec:
  imageVulnerabilityRequirements:
    maximumFixableSeverity: LOW
    maximumUnfixableSeverity: MEDIUM
    allowlistCVEs:
     - projects/goog-vulnz/notes/CVE-2023-21930