apiVersion: kritis.grafeas.io/v1beta1
kind: VulnzSigningPolicy
metadata:
  name: my-vsp
spec:
  imageVulnerabilityRequirements:
    maximumFixableSeverity: LOW
    maximumUnfixableSeverity: HIGH
    allowlistCVEs:
    - projects/goog-vulnz/notes/CVE-2023-0286
    - projects/goog-vulnz/notes/CVE-2023-0361