apiVersion: apps/v1
kind: Deployment
metadata:
  name: myspringbootapp
  labels:
    app: myspringbootapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myspringbootapp
  template:
    metadata:
      labels:
        app: myspringbootapp
    spec:
      containers:
      - name: myspringbootapp
        image: myspringbootapp
        env:
        - name: LOCATION
          value: development
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: gke-cloud-sql-secrets
              key: databaseip         
        - name: DB_PORT
          value: "5432"  
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: gke-cloud-sql-secrets
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: gke-cloud-sql-secrets
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: gke-cloud-sql-secrets
              key: database

