apiVersion: v1
kind: Service
metadata:
  name: myspringbootapp
  labels:
    app: myspringbootapp
spec:
  ports:
  - name: http
    port: 8080
  type: LoadBalancer
  selector:
    app: myspringbootapp 