apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-configmap
data:
  message: "hello there"
  test: "an example test property"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myspringbootapp
  name: myspringbootapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myspringbootapp
  strategy: { }
  template:
    metadata:
      labels:
        app: myspringbootapp
    spec:
      volumes:
        - name: demo-config-volume
          configMap:
            name: demo-configmap
      containers:
        - image: myspringbootapp
          imagePullPolicy: IfNotPresent
          name: myspringbootapp
          volumeMounts:
            - mountPath: /myconfigs
              name: demo-config-volume
          env:
          - name: JAVA_TOOL_OPTIONS
            value: "-XX:MaxRAMPercentage=70"
          resources:
            requests:
              memory: "800Mi"
              cpu: "500m"
            limits:
              memory: "800Mi"
             # cpu: "2000m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            periodSeconds: 3
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: 8080
          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            failureThreshold: 30
            periodSeconds: 10              
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 10" ]
