apiVersion: v1
kind: Service
metadata:
  labels:
    app: myspringbootapp
  name: myspringbootapp
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: myspringbootapp
  type: LoadBalancer
